# Generated by Django 6.0.5 on 2026-05-29 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MTCars",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.TextField(db_column="NAME")),
                ("mpg", models.FloatField(db_column="MPG")),
                ("cyl", models.IntegerField(db_column="CYL")),
                ("disp", models.FloatField(db_column="DISP")),
                ("hp", models.IntegerField(db_column="HP")),
                ("wt", models.FloatField(db_column="WT")),
                ("qsec", models.FloatField(db_column="QSEC")),
                ("vs", models.IntegerField(db_column="VS")),
                ("am", models.IntegerField(db_column="AM")),
                ("gear", models.IntegerField(db_column="GEAR")),
            ],
            options={
                "db_table": "MTCars",
                "ordering": ["id"],
                "managed": True,
            },
        ),
    ]
